services:
  cargocare-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    restart: unless-stopped
    volumes:
      - $WORKDIR/config/cargocare/appsettings.json:/app/appsettings.json

    networks:
      - default

networks:
  default:
    external: true
    name: connet
